(deftheme noah-custom
  "Created 2020-07-11.")

(custom-theme-set-faces
 'noah-custom
 '(cursor ((t (:inverse-video t :foreground "#fdf6e3" :background "indian red"))))
 '(fixed-pitch ((t (:family "Anka/Coder" :height 75))))
 '(variable-pitch ((t (:family "Helvetica Neue LT Std"))))
 '(escape-glyph ((t (:foreground "magenta" :weight bold))))
 '(minibuffer-prompt ((t (:background "black" :foreground "white" :weight bold))))
 '(highlight ((t (:background "red" :foreground "white" :underline nil))))
 '(region ((t (:background "color-238"))))
 '(shadow ((t (:foreground "brightmagenta"))))
 '(secondary-selection ((t (:weight bold :foreground "light goldenrod" :background "#FBE448"))))
 '(trailing-whitespace ((t (:background "#FFFF57"))))
 '(font-lock-builtin-face ((t (:foreground "blue" :slant normal :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "blue" :slant normal))))
 '(font-lock-comment-face ((t (:background "black" :foreground "blue" :slant italic :weight normal))))
 '(font-lock-constant-face ((t (:foreground "red" :slant italic :weight normal))))
 '(font-lock-doc-face ((t (:background "black" :foreground "blue" :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "cyan" :underline nil :slant italic :weight normal))))
 '(font-lock-negation-char-face ((t (:foreground "yellow" :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "magenta" :slant italic))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit nil :foreground "magenta" :weight normal))))
 '(font-lock-regexp-grouping-construct ((t (:inherit nil :foreground "yellow" :weight bold))))
 '(font-lock-string-face ((t (:background "black" :foreground "red" :slant italic))))
 '(font-lock-type-face ((t (:foreground "green" :slant normal :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "white" :underline nil :slant italic :weight light))))
 '(font-lock-warning-face ((t (:weight bold :foreground "red" :inherit (error)))))
 '(button ((t (:background "#333333" :foreground "blue" :underline t))))
 '(link ((t (:foreground "blue" :underline t :weight normal))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#E5786D"))))
 '(fringe ((t (:foreground "#9B9B9B" :background "#EDEDED"))))
 '(header-line ((t (:weight bold :underline (:color "black" :style line) :overline "black" :box (:line-width 2 :color "#fdf6e3" :style unspecified) :foreground "black" :background "#FFFF88"))))
 '(tooltip ((t (:foreground "black" :background "light yellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:weight bold :underline (:color "#cccec4" :style line) :overline "#eee8d5" :box (:line-width 1 :color "#1A2F54" :style nil) :foreground "#85CEEB" :background "#335EA8"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "black" :background "white" :inherit (julie-strong-1-face)))))
 '(mode-line-emphasis ((t (:weight bold :foreground "white"))))
 '(mode-line-highlight ((t (:inverse-video t :foreground "yellow"))))
 '(mode-line-inactive ((t (:underline (:color "#cccec4" :style line) :overline "#eee8d5" :box (:line-width 1 :color "#4E4E4C" :style nil) :foreground "#F0F0EF" :background "#9B9C97" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :underline (:color "#FF9632" :style line) :background "#FDBD33"))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#FF9999"))))
 '(lazy-highlight ((t (:weight normal :underline (:color "#FF9632" :style line) :foreground "#fdf6e3" :background "#FFFF00"))))
 '(match ((t (:weight bold :foreground "#586e75" :background "#FBE448"))))
 '(next-error ((t (:underline nil :background "#FFF876"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(font-lock-keyword-face ((t (:foreground "yellow"))))
 '(haskell-operator-face ((t (:inherit font-lock-variable-name-face :foreground "yellow"))))
 '(show-paren-match ((t (:background "brightcyan"))))
 '(show-paren-mismatch ((t (:background "red"))))
 '(agda2-highlight-keyword-face ((t (:foreground "yellow"))))
 '(agda2-highlight-module-face ((t (:foreground "green" :slant italic))))
 '(agda2-highlight-operator-face ((t (:foreground "yellow"))))
 '(agda2-highlight-datatype-face ((t (:foreground "green"))))
 '(agda2-highlight-record-face ((t (:foreground "green" :weight bold))))
 '(agda2-highlight-number-face ((t (:foreground "red" :slant italic))))
 '(agda2-highlight-primitive-face ((t (:foreground "cyan"))))
 '(agda2-highlight-string-face ((t (:foreground "red" :slant italic))))
 '(agda2-highlight-inductive-constructor-face ((t (:foreground "brightcyan"))))
 '(agda2-highlight-primitive-type-face ((t (:foreground "blue"))))
 '(agda2-highlight-macro-face ((t (:foreground "magenta"))))
 '(agda2-highlight-dotted-face ((t nil)))
 '(agda2-highlight-function-face ((t (:foreground "cyan"))))
 '(custom-link ((t (:inherit (link)))))
 '(agda2-highlight-unsolved-constraint-face ((t (:background "red" :foreground "white"))))
 '(agda2-highlight-unsolved-meta-face ((t (:background "red"))))
 '(agda2-highlight-error-face ((t (:underline (:color foreground-color :style line) :foreground "red"))))
 '(agda2-highlight-symbol-face ((t (:foreground "magenta"))))
 '(hl-line ((t (:background "color-243"))))
 '(linum ((t (:foreground "yellow"))))
 '(agda2-highlight-postulate-face ((t (:foreground "brightmagenta" :weight bold))))
 '(agda2-highlight-field-face ((t (:foreground "cyan" :weight bold))))
 '(linum-current-line-number-face ((t (:inherit linum :background "black" :foreground "red" :weight bold))))
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default")))))

(provide-theme 'noah-custom)
