(deftheme noah-custom-gui
  "Created 2020-12-21.")

(custom-theme-set-faces
 'noah-custom-gui
 '(cursor ((t (:inverse-video t :foreground "#fdf6e3" :background "#f81ce5"))))
 '(fixed-pitch ((t (:family "Anka/Coder" :height 75))))
 '(variable-pitch ((t (:family "Helvetica Neue LT Std"))))
 '(escape-glyph ((t (:foreground "#b48ead" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "white" :weight bold))))
 '(highlight ((t (:background "#bf616a" :foreground "white" :underline nil))))
 '(region ((t (:background "color-238"))))
 '(shadow ((t (:foreground "#caa6ec"))))
 '(secondary-selection ((t (:weight bold :foreground "light goldenrod" :background "#FBE448"))))
 '(trailing-whitespace ((t (:background "#FFFF57"))))
 '(font-lock-builtin-face ((t (:foreground "#5e81ac" :slant normal :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5e81ac" :slant normal))))
 '(font-lock-comment-face ((t (:foreground "#5e81ac" :slant italic :weight normal))))
 '(font-lock-constant-face ((t (:foreground "#bf616a" :slant italic :weight normal))))
 '(font-lock-doc-face ((t (:foreground "#5e81ac" :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "#88c0d0" :underline nil :slant italic :weight normal))))
 '(font-lock-negation-char-face ((t (:foreground "#EBCB8B" :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#b48ead" :slant italic))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit nil :foreground "#b48ead" :weight normal))))
 '(font-lock-regexp-grouping-construct ((t (:inherit nil :foreground "#ebcb8b" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#bf616a" :slant italic))))
 '(font-lock-type-face ((t (:foreground "#A3BE8C" :slant normal :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "white" :underline nil :slant italic :weight light))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#bf616a" :inherit (error)))))
 '(button ((t (:background "#333333" :foreground "#5e81ac" :underline t))))
 '(link ((t (:foreground "#5e81ac" :underline t :weight normal))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#E5786D"))))
 '(fringe ((t (:background "gray35" :foreground "#bf616a"))))
 '(header-line ((t (:weight bold :underline (:color "black" :style line) :overline "black" :box (:line-width 2 :color "#fdf6e3" :style unspecified) :foreground "black" :background "#FFFF88"))))
 '(tooltip ((t (:foreground "black" :background "light yellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:weight bold :underline (:color "#cccec4" :style line) :overline "#eee8d5" :box (:line-width 1 :color "#1A2F54" :style nil) :foreground "#85CEEB" :background "#335EA8"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "black" :background "white" :inherit (julie-strong-1-face)))))
 '(mode-line-emphasis ((t (:weight bold :foreground "white"))))
 '(mode-line-highlight ((t (:inverse-video t :foreground "#ebcb8b"))))
 '(mode-line-inactive ((t (:underline (:color "#cccec4" :style line) :overline "#eee8d5" :box (:line-width 1 :color "#4E4E4C" :style nil) :foreground "#F0F0EF" :background "#9B9C97" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :underline (:color "#FF9632" :style line) :background "#FDBD33"))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#FF9999"))))
 '(lazy-highlight ((t (:weight normal :underline (:color "#FF9632" :style line) :foreground "#fdf6e3" :background "#FFFF00"))))
 '(match ((t (:weight bold :foreground "#586e75" :background "#FBE448"))))
 '(next-error ((t (:underline nil :background "#FFF876"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(font-lock-keyword-face ((t (:foreground "#EBCB8B"))))
 '(haskell-operator-face ((t (:foreground "#EBCB8B" :inherit font-lock-variable-name-face))))
 '(show-paren-match ((t (:background "8fbcbb"))))
 '(show-paren-mismatch ((t (:background "#bf616a"))))
 '(custom-link ((t (:inherit (link)))))
 '(hl-line ((t (:background "gray35"))))
 '(linum ((t (:foreground "#EBCB8B"))))
 '(linum-current-line-number-face ((t (:inherit linum :foreground "#bf616a" :weight bold))))
 '(default ((t (:inherit nil :stipple nil :background "#2E3440" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "default" :family "default")))))

(provide-theme 'noah-custom-gui)
