call plug#begin('~/.vim/plugged')

Plug 'johngrib/vim-game-code-break'

call plug#end()

execute pathogen#infect()

"Enable syntax highlighting and inednting
syntax on
filetype on
filetype plugin indent on

"Colorscheme
"let g:nord_underline = 1
"let g:nord_cursor_line_number_background = 1
" for some reason, the colorscheme that i'm used to is the default for light
" background, but hey, it looks good in my terminal
colorscheme peachpuff

"Custom key mappings
inoremap jk <ESC>

"Make it so we can delete indent and across lines in insert mode
set backspace=indent,eol,start

"By default, expand tabs to four spaces, but not in some filetypes
set softtabstop=4
set shiftwidth=4
set expandtab
"autocmd Filetype html setlocal tabstop=2

"Highlight current line
set cursorline
hi CursorLine   cterm=NONE ctermbg=243 ctermfg=NONE

set nocompatible
set number
set nowrap
set showmode
set tw=80
set smartcase
set smarttab
set smartindent
set autoindent
set incsearch
set mouse=a
set history=1000
set clipboard=unnamedplus,autoselect

set completeopt=menuone,menu,longest

set wildignore+=*\\tmp\\*,*.swp,*.swo,*.zip,.git,.cabal-sandbox
set wildmode=longest,list,full
set wildmenu
set completeopt+=longest

set t_Co=256

set cmdheight=1

"Config for c++
let g:syntastic_cpp_compiler_options = "-std=c++11 -Wall -Wextra -Wpedantic"

"Name of cpp config file
let g:syntastic_cpp_config_file = '.syntastic_cpp_config_noah'

"Config for idris
let g:syntastic_idris_checkers=['idris']
au FileType idris setl tw=0

"Stuff for Elm
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:elm_syntastic_show_warnings = 1
let g:elm_format_autosave = 0
let g:syntastic_elm_checkers = [ 'elm_make' ]

"Stuff for Haskell syntax highlighting
let g:haskell_classic_highlighting = 1
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords


"Stuff for sml
" Uncomment to try out conceal characters
au FileType sml setlocal conceallevel=2

" Uncomment to try out same-width conceal characters
let g:sml_greek_tyvar_show_tick = 1

"Nerdtree config settings
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1


"Stuff for the vim-airline plugin
let g:airline#extensions#syntastic#enabled = 1

"if !exists('g:airline_symbols')
"    let g:airline_symbols = {}
"endif
"let g:airline_symbols.space = "\ua0"

let g:airline_powerline_fonts = 1
let g:airline_theme = "nord"
"let g:airline_solarized_bg = 'dark'
